### ISSUE TITLE
Eytukan loves his dank memes, is that considered an issue?

### ISSUE THREAD

**Issue by ghost** [kingcodefish/star-wars-the-final-frontier#1]
Is it considered an issue that I am not included in the fun? I can make any details and graphics you need. Plus the game idea sounds pretty cool.

**Comment by kingcodefish** [comment]
I'm not sure, me and AlexT have been pretty in-depth with this. I'll have to ask him, and the storyline file is not NEARLY finished at all. This is a direct half/half development team between me and AlexT at the moment. What in particular do you want to help with? It can be graphics, design, etc.

**Comment by ghost** [comment]
I do like my dank memes. I have a lot of graphics that you could already use and lots of ideas. I read through your ideas 2 times and found a few things that I definitely could help with. You could use General Hux as an enemy because he is a very powerful character and probably has more power than Phasma.

**Comment by kingcodefish** [comment]
This is a top-down game though, the reason for that is due to the complexity of isometric, and the lack of depth in a side-scroller. We're not trying to pixelate a bunch of stuff, but your graphics have to be able to be bitmapped without distortions. We're looking for 32x32 characters is what I'm thinking ATM. Do you have any ideas for the story then? You could help storyboard.

**Comment by ghost** [comment]
I had to read that first sentence at least 3 times. I can definitely help with the storyboard. If you need any menu graphics I got them (I am hoping the menu is not isometric).

**Comment by kingcodefish** [comment]
Nah, the menu is perfectly fine. It's only 3D. jk jk Anyways, we would like something for when the player selects his side, what series, shop, etc. But again, we're not that far, so storyboarding is what we're doing ATM.

**Comment by kingcodefish** [comment]
Go here and you can chat about this Github: https://gitter.im/kingcodefish/star-wars-the-final-frontier

**Comment by ghost** [comment]
sorry I went to bed.

**Comment by kingcodefish** [comment]
Lol, I happen to be on right when you are :P

**Comment by kingcodefish** [comment]
Again, chat here: https://gitter.im/kingcodefish/star-wars-the-final-frontier This issue has been closed.

**Comment by ghost** [comment]
I can't chat right now. I am at school. I can chat later
