### ISSUE TITLE
Going to edit during 4:00-6:00 every day (ish)

### ISSUE THREAD

**Issue by IndieKA** [kingcodefish/star-wars-the-final-frontier#8]
I know this isn't necessarily a issue but considering I'm the new editor I will be on mainly 4:00 thru 6:00.

**Comment by kingcodefish** [comment]
Alright, you _have_ to edit today though.

**Comment by IndieKA** [comment]
Okay

**Comment by kingcodefish** [comment]
Alright, good start, just make sure you stay semi-active, I don't want dead users lol. Remember SoS? :P

**Comment by IndieKA** [comment]
I made a new issue, see to it quickly?

**Comment by kingcodefish** [comment]
Oops, didn't see this. If you want to ask simple questions unrelated to the project like that, please caht on Gitter or your MathIM, considering you mom doesn't want you on Gitter. We never curse BTW. If anyone does, they will be warned before being promptly kicked. As that's not what this project is about. But for the time being, go to MathIM here: http://mathim.com/rektka99

**Comment by kingcodefish** [comment]
This is now closed.
