### ISSUE TITLE
How many edits per day?

### ISSUE THREAD

**Issue by IndieKA** [kingcodefish/star-wars-the-final-frontier#9]
Hi KingCodeFish,

Since you're pretty on task with this game, how many edits per day?
I am actually writing most of the code at Khan Academy, so it doesn't look like I'm editing here much on GitHub... I'll copy and paste everything into new files stored in the game folder.

Thanks,
Indie.

PS - I hope you have no problem with this.

**Comment by kingcodefish** [comment]
No specific number, just at least have 1 every other day at the very least. I have exceptions for vacations and stuff. (Eytukan is going to be absent until Sunday)

**Comment by kingcodefish** [comment]
BTW, I have a working demo here: https://www.khanacademy.org/computer-programming/star-wars-the-final-frontier/6136022677454848

**Comment by IndieKA** [comment]
Oh thank you. ;-; 
I'm keeping my edits private because somehow others are seeing the edits on this org. My neighbor was talking about it yesterday outside and I was all o_O
Doing the intro now, and I did the collide function.

**Comment by kingcodefish** [comment]
For real, XD. I have to test the collisions, again, not sure how we want to deal with entities yet, not that far. Come back to Gitter and we can talk about it, you left too soon, I was doing something.
